# Generated by Django 4.0.1 on 2022-01-16 16:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("yatsim_dashboard", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="guests",
            field=models.ManyToManyField(
                blank=True,
                related_name="accessible_rooms",
                related_query_name="accessible_room",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="Cell",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("x", models.PositiveSmallIntegerField()),
                ("y", models.PositiveSmallIntegerField()),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("0", "Blank"),
                            ("1", "Straight"),
                            ("2", "Curved"),
                            ("3", "Y Junction"),
                            ("4", "Y Junction Mirrored"),
                            ("5", "X Junction"),
                            ("6", "Cross Roads"),
                            ("7", "Cross Bridge"),
                            ("8", "Station"),
                        ],
                        max_length=1,
                    ),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[
                            ("0", "NORTH"),
                            ("1", "EAST"),
                            ("2", "SOUTH"),
                            ("3", "WEST"),
                        ],
                        max_length=1,
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("0", "Counter Clockwise Routing"),
                            ("1", "Straight Routing"),
                            ("2", "Clockwise Routing"),
                        ],
                        max_length=1,
                        null=True,
                    ),
                ),
                (
                    "room_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cells",
                        related_query_name="cell",
                        to="yatsim_dashboard.room",
                    ),
                ),
            ],
            options={
                "unique_together": {("room_id", "x", "y")},
            },
        ),
    ]
