# Generated by Django 4.0.1 on 2022-01-18 18:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("yatsim_dashboard", "0002_alter_room_guests_cell"),
    ]

    operations = [
        migrations.CreateModel(
            name="Train",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.CharField(max_length=32)),
                ("length", models.PositiveSmallIntegerField()),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="yatsim_dashboard.cell",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Wagon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("x", models.PositiveSmallIntegerField()),
                ("y", models.PositiveSmallIntegerField()),
                (
                    "direction",
                    models.CharField(
                        choices=[
                            ("0", "NORTH"),
                            ("1", "EAST"),
                            ("2", "SOUTH"),
                            ("3", "WEST"),
                        ],
                        max_length=1,
                    ),
                ),
                (
                    "train",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="yatsim_dashboard.train",
                    ),
                ),
            ],
        ),
    ]
