# Generated by Django 4.0.1 on 2022-01-18 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("yatsim_dashboard", "0003_train_wagon"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="wagon",
            options={"ordering": ("-sequence_id",)},
        ),
        migrations.AddField(
            model_name="train",
            name="room_id",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="yatsim_dashboard.room",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="wagon",
            name="sequence_id",
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
