# Generated by Django 4.0.2 on 2022-02-06 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("yatsim_dashboard", "0005_alter_wagon_options_alter_cell_direction"),
    ]

    operations = [
        migrations.AlterField(
            model_name="train",
            name="source",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="yatsim_dashboard.cell"
            ),
        ),
    ]
